### ISSUE TITLE
Configuración definitiva de las etiquetas del proyecto

### ISSUE THREAD

**Issue by jesusyesares** [jesusyesares/hb-comunicacion-wordcamp#107]
Hay que pasar las etiquetas configuradas en la organización a las del proyecto `spain-handbook`

https://github.com/organizations/WPES/settings/repository-defaults

https://github.com/WPES/spain-handbook/labels

El motivo de pasarlas al proyecto es porque se crearon en la organización como etiquetas por defecto de la misma, y se necesitaría que estuviesen dentro del proyecto para que puedan ser transferidas correctamente.

**Comment by javiercasares** [comment]
Hecho!
