### ISSUE TITLE
Ampliar manual de GitHub para arquitectura de la información

### ISSUE THREAD

**Issue by javiercasares** [jesusyesares/hb-comunicacion-wordcamp#112]
Hay que explicar en el Manual de GitHub cómo va a funcionar la arquitectura de la información, o sea, carpetas, subcarpetas, y cómo será eso en la web.

Afecta a:
[/manuales/github](https://github.com/WPES/spain-handbook/tree/main/manuales/github)

**Comment by mpc** [comment]
¿Puedes dar más detalles de como debería ser?, ¿una página en la raíz del proyecto?, ¿alguna forma específica?

**Comment by javiercasares** [comment]
Ya está hecho en https://es.wordpress.org/team/handbook/manuales/github/
