### ISSUE TITLE
Sugerencia: Mantener los nombres de las carpetas y archivos igual que global

### ISSUE THREAD

**Issue by sejas** [jesusyesares/hb-comunicacion-wordcamp#121]
# Problema

Entiendo que la fuente de la verdad de las páginas que se sincronizan están definidas en https://github.com/WPES/spain-handbook/blob/main/bin/handbook-manifest.json lo que nos permite realmente usar cualquier nombre de carpeta y de archivo.

Por ahora estamos usando nombres en español y la divergencia con Global será total, lo que será más difícil encontrar las diferencias con la versión en inglés.

Un ejemplo son las carpetas `resources`, `themes`, y `performance`, que en las carpetas de español las llamamos `recursos`, `temas` y `rendimiento`.

<img width="1725" alt="correspondencia-en-los-nombres-en-laestructura-carpetas" src="https://github.com/WPES/spain-handbook/assets/779993/4c7cf676-d614-44ea-a58a-fa62610553f2">

Idealmente, me encantaría que cuando se añada o modifique un archivo en la versión inglesa, se cree un Issue o incluso PR señalando ambos archivos de forma automática. Si comparten el mismo nombre de carpeta y archivos ("path") ese problema es trivial.

# Solución

Mi sugerencia es usar la misma estructura de archivos con los mismos nombres de directorio y de archivos que https://github.com/WordPress/Advanced-administration-handbook. Esto además nos ayudará a detectar los archivos huérfanos de forma inmediata. Un simple diff entre la estructura de ambos repositorios nos lo daría. Entendiendo un huérfano como una página específica que es relevante para el idioma Español.

Además otro beneficio de esta solución es que cualquiera podría entrar en un repo y entender que corresponde a que de forma visual. Imagínate entrar en el repo en japonés e intentar ver qué páginas huérfanas tienen ellos.

@javiercasares @jesusyesares  ¿Qué pensáis?

**Comment by mpc** [comment]
Yo veo esta sugerencia muy razonable.

**Comment by javiercasares** [comment]
Estamos hablando de manuales en español… otra cosa es que ajustemos algunas de las carpetas que hay, pero no acabo de ver que "core" lo llamemos "núcleo", o que pongamos las URL en inglés cuando haya que navegar por la web en español.

**Comment by sejas** [comment]
Gracias por la respuesta @mpc y @javiercasares.

Mi propuesta viene desde la suposición de que la URL viene determinada por el `slug` y lo podemos poner en español independientemente de como llamemos a la carpeta:

```
	"manuales": {
		"title": "Documentación global",
		"slug": "manuales",
		"markdown_source": "https:\/\/github.com\/wordpress\/hosting-handbook\/blob\/master\/manuales\/index.md",
		"parent": "index",
		"order": 1
	},
```

**Comment by javiercasares** [comment]
Hay que tener en cuenta que este Handbook de España, no es una traducción de nada del inglés. Es 100% contenido propio o, en algún caso, alguna página concreta del inglés (fuera de control) que se necesite traer a España mientras comienza el proyecto de traducción "de todo", por lo que no podemos basarnos en ninguna otra documentación.

Esto es 100% creado por nosotros, para nosotros. Tampoco hay idea de que esto nuestro se vaya a traducir a otros idiomas. Esto aplica exclusivamente a la Comunidad WordPress España.

**Comment by sejas** [comment]
Genial. Gracias por la aclaración. En ese caso, lo había entendido mal.
Creía que el idioma principal era el inglés, si se quería crear un contenido se iba a hacer primero en inglés, y luego en el resto de idiomas, y que las páginas huérfanas eran una excepción y no la regla.

Gracias por tener en cuenta mi propuesta 🙏 . Voy a cerrar el issue.

Y me encantaría poder ayudar con este proyecto, ya sea escribir contenido o automatizar "sincronizaciones".
