### ISSUE TITLE
Cómo crear una cuenta en GitHub

### ISSUE THREAD

**Issue by javiercasares** [jesusyesares/hb-comunicacion-wordcamp#126]
https://github.com/WPES/spain-handbook/blob/main/manuales/github/cuenta.md

- [x] Registrarse en GitHub
- [x] Activar el 2FA
- [x] Instalarse la App del Móvil
- [x] Aplicación de Escritorio

**Comment by javiercasares** [comment]
Se puede usar contenido de base de aquí:
https://github.com/WPES/spain-handbook/blob/main/manuales/github/version-base.md

**Comment by jesusyesares** [comment]
Revisar el #277 y marcar una vez publicado
