### ISSUE TITLE
Editar imágenes para GitHub

### ISSUE THREAD

**Issue by javiercasares** [jesusyesares/hb-comunicacion-wordcamp#128]
https://github.com/WPES/spain-handbook/blob/main/manuales/github/editarimagen.md

- [ ] Preparar la imagen offline
- [ ] Subir la imagen
- [ ] Enlazar la imagen

**Comment by javiercasares** [comment]
Se puede aprovechar contenido de:
https://github.com/WPES/spain-handbook/blob/main/manuales/github/version-base.md

**Comment by jesusyesares** [comment]
Este apartado lo he trasladado a otro manual y ahora hay que adaptarla al nuevo manual de imágenes.

https://github.com/WPES/spain-handbook/pull/169

**Comment by moranjosep** [comment]
Hola @jesusyesares . ¿Puedes decirme cómo llevamos este issue? 

Un saludo.
