### ISSUE TITLE
Chat de España y Global

### ISSUE THREAD

**Issue by javiercasares** [jesusyesares/hb-comunicacion-wordcamp#134]
Basado en:
https://es.wordpress.org/guias/chat/

Crear esto:
https://github.com/WPES/spain-handbook/blob/main/equipo/chat.md

**Comment by adrianaseguracom** [comment]
Hola. Quiero encargarme de esto. He encontrado esta otra entrada: https://es.wordpress.org/2016/10/02/slack-wordpress-espana/ 

La propuesta es fusionar.

**Comment by jesusyesares** [comment]
Perfecto, te lo asigno a ti.

**Comment by javiercasares** [comment]
Migrado en #161
