### ISSUE TITLE
Revisar documentación hecha

### ISSUE THREAD

**Issue by anagavilan** [jesusyesares/hb-comunicacion-wordcamp#14]
https://github.com/WPES/spain-handbook/blob/master/manual-github/README.md

**Comment by jesusyesares** [comment]
He organizado un poco mejor los contenidos, basándome en el trabajo que ha hecho @AlexMusetti.

He extraído del manual de comunicación toda mención a Github, pasándolo todo al documento principal del repositorio, puesto que es válido para todos los manuales que se hagan.

También he eliminado todos aquellos párrafos que eran redundantes ya que @AlexMusetti los había ubicado en el manual de Github, con un orden más lógico.

Por otro lado, he corregido algunas cuestiones de formato y algunos enlaces que estaban con ruta absoluta apuntando a repositorios personales para que su ruta fuera relativa y apuntasen al repositorio oficial.

Por último, he creado un mapa mental que puede ayudar a visualizar mejor la estructura actual del repositorio en cada momento.
