### ISSUE TITLE
Manual de SEO

### ISSUE THREAD

**Issue by jestebad** [jesusyesares/hb-comunicacion-wordcamp#144]
Hay que crear un manual de SEO para facilitar la información para aquellos que publican contenidos en las "noticias" de WordPress.

- [ ] Manual de encabezados
- [ ] Manual de Meta Etiquetas (Títulos y meta descripciones)
- [ ] Manual optimización de imágenes
- [ ] Manual de canibalizaciones
- [ ] Manual de Keyword Research
- [ ] Manual de redirecciones
- [ ] Manual de URL
- [ ] Manual de Rich Snippet
- [ ] Manual de WPO
- [ ] Manual de Robots.txt

**Comment by javiercasares** [comment]
Por mi K; aunque hay que tener en cuenta que sí y que no se puede hacer en un post de WordPress (en el post, no en el sitio, al que nos e puede hacer nada)...

Por ejemplo:

Manual de Meta Etiquetas (Títulos y meta descripciones)
Manual de redirecciones
Manual de Rich Snippet
Manual de WPO
Manual de Robots.txt

Estos no creo que sea necesario documentarlos, porque no es útil para lo que se puede hacer en wordpress.org.

Como digo, creo que el foco debe estar en el contenido de un post, pero poco más...

**Comment by moranjosep** [comment]
Los apartados que proceden se están distribuyendo en otras secciones. Se cierra esta tarea que había quedado como tarea fantasma.

Gracias y un saludo.
