### ISSUE TITLE
[Wordcamp: Badge de Ponente no aparece]

### ISSUE THREAD

**Issue by moranjosep** [jesusyesares/hb-comunicacion-wordcamp#164]
Tras mi primera ponencia en Madrid no aparece el Badge de WordCamp Speaker. 
En este caso, la forma correcta de actuar debe ser la siguiente: 
1.  Entrar en la ficha de la WordCamp del ponente.
2. Darle a guardar de nuevo, validando que el nombre de usuario sea el correcto.

Con estos sencillos pasos se queda actualizado el perfil del ponente.

**Comment by jesusyesares** [comment]
@moranjosep, cuando puedas, ¿puedes documentar esto y pasarlo al handbook, en la sección de eventos o en la de Meta?

Gracias :)

**Comment by moranjosep** [comment]
Este finde lo dejo hecho.
Saludos.

**Comment by jesusyesares** [comment]
Tranquilo, no hay prisa :)

**Comment by jesusyesares** [comment]
@moranjosep, cuando puedas, ¿puedes confirmarme que esto está hecho y ponerme la URL exacta del documento en github para que lo publique?

Gracias.

**Comment by moranjosep** [comment]
Si...

**Comment by jesusyesares** [comment]
Ok, solucionado y cerrado con el PR #280
