### ISSUE TITLE
[Manual GitHub] Revisar Paso 1 Crear una cuenta en GitHub

### ISSUE THREAD

**Issue by jesusyesares** [jesusyesares/hb-comunicacion-wordcamp#235]
Esta tarea es para alguien principiante, para que revise el proceso de crear una cuenta en GitHub, y compruebe que todo funciona perfectamente.

Si encuentras algún punto de fricción, no dudes en corregir y/o añadir sugerencias en este Issue, en los comentarios.

Archivo a editar: https://github.com/WordPress/spain-handbook/blob/main/manuales/github/crear/index.md

Publicado en: https://es.wordpress.org/team/handbook/manuales/github/crear/

**Comment by pilargarciaab** [comment]
Hola! ¿Puedes asignarme este Issue? Gracias

**Comment by jesusyesares** [comment]
Queda pendiente de:
- [x] Revisar por GTE (@nilovelez)
- [ ] Publicar en la web
