### ISSUE TITLE
[Manual GitHub] Paso 2: Enlazar tu perfil de WordPress con GitHub

### ISSUE THREAD

**Issue by jesusyesares** [jesusyesares/hb-comunicacion-wordcamp#236]
Esta tarea es para alguien principiante, para que revise el proceso de enlazar su perfil de WordPress con GitHub, y compruebe que todo funciona perfectamente.

Si encuentras algún punto de fricción, no dudes en corregir y/o añadir sugerencias en este Issue, en los comentarios.

Archivo a editar: https://github.com/WordPress/spain-handbook/blob/main/manuales/wordpress/sincronizar/index.md

Publicado en: https://es.wordpress.org/team/handbook/manuales/wordpress/sincronizar/

**Comment by moranjosep** [comment]
Hola Jesús, revisados los enlaces y están correctos. Yo añadiría que una vez finalizada toda la operación de vincular GitHub con WordPress.org, debe aparecer el icono de GitHub a la derecha de la página como una red social enlazada, en el apartado:
 "find me on". Creo que es la prueba, que es la forma de saber si está realizado el proceso correctamente.

El resto lo he probado y está todo ok.

**Comment by jesusyesares** [comment]
Publicado
