### ISSUE TITLE
[Manual GitHub] Paso 3: Crear el contenido de Crear fork

### ISSUE THREAD

**Issue by jesusyesares** [jesusyesares/hb-comunicacion-wordcamp#237]
Esta tarea es para que quien lo edite pase el contenido desde el apartado _Crear Fork_ del siguiente documento a su documento correspondiente:

Origen: [https://github.com/WordPress/spain-handbook/blob/main/manuales/github/comofunciona/index.md#crear-un-fork
](https://github.com/WordPress/spain-handbook/blob/main/manuales/github/comofunciona/index.md#crear-un-fork
)
Destino: [https://github.com/WordPress/spain-handbook/blob/main/manuales/github/index.md
](https://github.com/WordPress/spain-handbook/blob/main/manuales/github/index.md
)
Si encuentras algún punto de fricción, no dudes en corregir y/o añadir sugerencias en este Issue, en los comentarios.

Publicado en: [https://es.wordpress.org/team/handbook/manuales/github/fork/](https://es.wordpress.org/team/handbook/manuales/github/fork/)

**Comment by AkireOrl** [comment]
Este lo tengo yo ^^
