### ISSUE TITLE
[Manual GitHub] Crear contenido de Paso 4: Revisar los issues

### ISSUE THREAD

**Issue by jesusyesares** [jesusyesares/hb-comunicacion-wordcamp#238]
Esta tarea es para crear el contenido, explicando cómo revisar un Issue, y las diferentes posibilidades que hay (ver notas de edición).

Archivo: https://github.com/WordPress/spain-handbook/blob/main/manuales/github/issues/index.md

Si encuentras algún punto de fricción, no dudes en corregir y/o añadir sugerencias en este Issue, en los comentarios.

Publicado en: https://es.wordpress.org/team/handbook/manuales/github/issues/

**Comment by AkireOrl** [comment]
Esta también la tengo yo  ^^

**Comment by moranjosep** [comment]
Hola Erika, ¿Cómo está esta tarea?
Un saludo !! ;D
