### ISSUE TITLE
[Manual GitHub] Pasar el contenido del Paso 7 Crear un Commit

### ISSUE THREAD

**Issue by jesusyesares** [jesusyesares/hb-comunicacion-wordcamp#242]
Esta tarea es para que quien lo edite pase el contenido desde el apartado Crear una instantánea de los cambios a su documento correspondiente:

Origen: https://github.com/WordPress/spain-handbook/blob/main/manuales/github/comofunciona/index.md#validar-los-cambios-de-edici%C3%B3n

Destino: https://github.com/WordPress/spain-handbook/blob/main/manuales/github/commit/

Si encuentras algún punto de fricción, no dudes en corregir y/o añadir sugerencias en este Issue, en los comentarios.

Publicado en: https://es.wordpress.org/team/handbook/manuales/github/commit/

**Comment by moranjosep** [comment]
Hola. Podéis asignarme el Issue #242.

Un saludo.

**Comment by jesusyesares** [comment]
@moranjosep, cuando puedas dime cómo llevas esta tarea y si necesitas ayuda.
