### ISSUE TITLE
[Manual GitHub] Pasar el contenido del Paso 9: Pull Request

### ISSUE THREAD

**Issue by jesusyesares** [jesusyesares/hb-comunicacion-wordcamp#243]
Esta tarea es para que quien lo edite pase el contenido desde el apartado Crear Pull Request del siguiente documento a su documento correspondiente:

Origen: https://github.com/WordPress/spain-handbook/blob/main/manuales/github/comofunciona/index.md#crear-un-pull-request

Destino: https://github.com/WordPress/spain-handbook/blob/main/manuales/github/pullrequest/

Si encuentras algún punto de fricción, no dudes en corregir y/o añadir sugerencias en este Issue, en los comentarios.

Publicado en: https://es.wordpress.org/team/handbook/manuales/github/pullrequest/

**Comment by moranjosep** [comment]
Solicito que me asignes este issue. Un saludo y gracias.

**Comment by jesusyesares** [comment]
Ya lo tienes, disculpa el retraso :)
