### ISSUE TITLE
[Accesibilidad] Página de Equipo

### ISSUE THREAD

**Issue by javiercasares** [jesusyesares/hb-comunicacion-wordcamp#245]
El equipo de Accesibilidad tiene una página disponible en el Handbook de WordPress España.

https://github.com/WordPress/spain-handbook/blob/main/accesibilidad/index.md

- [x] Revisar los contenidos actuales
- [ ] Actualizar o añadir nuevos contenidos
- [ ] Revisar las personas que pertenecen al equipo

Página destino: https://es.wordpress.org/team/handbook/accesibilidad/
Modelo: https://make.wordpress.org/accessibility/handbook/

**Comment by visanju** [comment]
Hola, asignadme este issue si os parece bien

**Comment by jesusyesares** [comment]
Se ha aprobado este PR de @visanju https://github.com/WordPress/spain-handbook/pull/295#event-12370884876

**Comment by jesusyesares** [comment]
@nilovelez ¿puedes revisar que esté todo correcto en el texto? 

Gracias :)
