### ISSUE TITLE
[Documentación] Página de Equipo

### ISSUE THREAD

**Issue by javiercasares** [jesusyesares/hb-comunicacion-wordcamp#248]
El equipo de Documentación tiene una página disponible en el Handbook de WordPress España.

https://github.com/WordPress/spain-handbook/blob/main/documentacion/index.md

- [ ] Revisar los contenidos actuales
- [ ] Actualizar o añadir nuevos contenidos
- [ ] Revisar las personas que pertenecen al equipo

**Comment by jesusyesares** [comment]
@javiercasares ¿puedes publicarla en el handbook?

**Comment by jesusyesares** [comment]
@javiercasares, creo que está para publicar. Cuando puedas hazlo.
