### ISSUE TITLE
[Hosting] Página de Equipo

### ISSUE THREAD

**Issue by javiercasares** [jesusyesares/hb-comunicacion-wordcamp#250]
El equipo de Hosting tiene una página disponible en el Handbook de WordPress España.

https://github.com/WordPress/spain-handbook/blob/main/hosting/index.md

- [x] Revisar los contenidos actuales
- [x] Actualizar o añadir nuevos contenidos
- [x] Revisar las personas que pertenecen al equipo

**Comment by javiercasares** [comment]
Relacionado: #302

**Comment by jesusyesares** [comment]
@nilovelez ¿puedes echarle una revisión?

Gracias
