### ISSUE TITLE
[Sostenibilidad] Página de Equipo

### ISSUE THREAD

**Issue by javiercasares** [jesusyesares/hb-comunicacion-wordcamp#254]
El equipo de Sostenibilidad tiene una página disponible en el Handbook de WordPress España.

https://github.com/WordPress/spain-handbook/blob/main/sostenibilidad/index.md

- [ ] Revisar los contenidos actuales
- [ ] Actualizar o añadir nuevos contenidos
- [ ] Revisar las personas que pertenecen al equipo

**Comment by jesusyesares** [comment]
Hola @CeliGaroe, para poder ubicar el manual de sostenibilidad en eventos, necesitaríamos que creéis esta página:

https://es.wordpress.org/make/handbook/sostenibilidad/

Desde la cual se enlazaría la página del manual, cuyo índice estará en `/sostenibilidad/eventos/`.

Podéis usar como modelo cualquiera de las páginas que ya están publicadas, y que tenéis su versión original aquí en GitHub.

Ya me dices.

**Comment by CeliGaroe** [comment]
Acabo de crear un nuevo pull request con los cambios. Me dices si he hecho algo más, por fi. ¡Gracias! 🙏
https://github.com/WordPress/spain-handbook/pull/358
