### ISSUE TITLE
[Documentación] Guía de Estilo

### ISSUE THREAD

**Issue by javiercasares** [jesusyesares/hb-comunicacion-wordcamp#261]
Habría que hacer una recopilación de distintas guías de estilo, ya existentes en español y en otros idiomas como referencia.

ESPAÑOL:
- https://developer.mozilla.org/es/docs/MDN/Writing_guidelines/Writing_style_guide
- https://usuario.cicese.mx/~mechevar/manual/
- https://es.wikipedia.org/wiki/Manual_de_estilo

OTROS IDIOMAS:
- https://make.wordpress.org/docs/style-guide/
- https://www.softcatala.org/guia-estil-de-softcatala/

**Comment by javiercasares** [comment]
@estelaris, @moranjosep

**Comment by visanju** [comment]
Guía de estilo de la Fundéu sobre el uso de letra redonda vs cursiva: https://www.fundeu.es/wp-content/uploads/2013/05/CursivasGuiaFundeu.pdf

**Comment by estelaris** [comment]
En este documento estamos empezando a mejorar la guia de estilo. Esta abierto para que cualquiera pueda aportar y despues tendremos sesiones para evaluar y aprobar las contribuciones

https://docs.google.com/document/d/1QI1SYrmYD0sXke-lM0VDgi4nKljZzYEU5j3R8RdIvKQ/edit?usp=sharing

**Comment by jesusyesares** [comment]
@javiercasares, @estelaris y @moranjosep ¿os parece que cerremos este Issue, puesto que se ha convertido en el proyecto completo de traducción y localización? No se trata de una tarea y, por tanto, no le veo mucho sentido que esté aquí.

Gracias :)

**Comment by javiercasares** [comment]
Sí, esto tenía sentido antes... por mí OK.
