### ISSUE TITLE
[Marketing y Documentación] Contributor Day WordCamp Zaragoza 2024

### ISSUE THREAD

**Issue by AkireOrl** [jesusyesares/hb-comunicacion-wordcamp#263]
Te damos la bienvenida al Contributor Day de la [WordCamp Zaragoza 2024](https://zaragoza.wordcamp.org/2024/).

Si es la primera vez que vienes o no sabes de qué va esto, te invitamos a que sigas leyendo y respondas a las siguientes preguntas.

## ¿Tienes cuenta de WordPress.org?

Si tienes cuenta (y ya has accedido), pasa a la siguiente pregunta.

Si no, dale una lectura a [Cuentas de WordPress.org](https://es.wordpress.org/team/handbook/manuales/wordpress/) en el Handbook, donde encontrarás [cómo crear tu cuenta de WordPress.org](https://es.wordpress.org/team/handbook/handbook/manuales/wordpress/crear/). Si ya tienes, y no te acuerdas de cómo acceder, quizá quieras ver [cómo recuperar tu cuenta de WordPress.org](https://es.wordpress.org/team/handbook/manuales/wordpress/#como-recuperar-tu-cuenta-de-wordpress-org).

## ¿Tienes cuenta de GitHub?

Si tienes cuenta (y ya has accedido), pasa a la siguiente pregunta.

Si no, dale una lectura a [Crear una cuenta en GitHub](https://es.wordpress.org/team/handbook/manuales/github/crear/) y, si quieres, una primera ojeada a [Cómo funciona GitHub](https://es.wordpress.org/team/handbook/manuales/github/comofunciona/) o pregúntale a la persona responsable de la mesa.

## ¿Tienes sincronizada la cuenta de GitHub con WordPress?

Esto es importante para que todo el trabajo que hagas en este repositorio aparezca en [tu perfil de WordPress](https://profiles.wordpress.org/me/).

Si lo tienes, en tu perfil aparecerá tu usuario de GitHub. Si no, puedes leer [Cómo sincronizar tu cuenta de WordPress.org con GitHub](https://es.wordpress.org/team/handbook/manuales/wordpress/sincronizar/).

### Tareas de nivel principiante (Prioritarias)

- [x] #235 
- [x] #236
- [x] #239 

### Tareas de nivel avanzado (Prioritarias)

- [x] #240 
- [x] #241
- [x] #242 

### Tareas Marketing
- [x] #144
- [ ] Crear Issues nuevos para artículos del blog a partir de [esta plantilla](https://github.com/WordPress/spain-handbook/blob/main/.github/ISSUE_TEMPLATE/nuevo-contenido-del-blog.md)

##Resumen de la jornada.

-Participantes en la mesa de Documentación : 2

-Tareas realizadas: información sobre el trabajo de documentación, registro y visualización en GitHub, enlazado de la nueva cuenta con la cuenta correspondiente de WordPress.org y tareas del Repositorio de Prueba para coger soltura con el flujo de trabajo. 

-Tickets cerrados: 0

-Tickets solicitados y en proceso: 1

**Comment by jesusyesares** [comment]
Hola @AkireOrl ¿puedes dejar un resumen del evento y, si está todo listo, cerrar el ticket?

**Comment by AkireOrl** [comment]
He añadido un breve resumen de lo que hicimos en el evento y lo he dado por cerrado. Gracias!
