### ISSUE TITLE
[Marketing y Documentación] Contributor Day WordCamp Torrelodones 2024

### ISSUE THREAD

**Issue by jesusyesares** [jesusyesares/hb-comunicacion-wordcamp#273]
Te damos la bienvenida al Contributor Day de la [WordCamp Torrelodones 2024](https://torrelodones.wordcamp.org/2024/).

Si es la primera vez que vienes o no sabes de qué va esto, te invitamos a que sigas leyendo y respondas a las siguientes preguntas.

## ¿Tienes cuenta de WordPress.org?

Si tienes cuenta (y ya has accedido), pasa a la siguiente pregunta.

Si no, dale una lectura a [Cuentas de WordPress.org](https://es.wordpress.org/team/handbook/manuales/wordpress/) en el Handbook, donde encontrarás [cómo crear tu cuenta de WordPress.org](https://es.wordpress.org/team/handbook/handbook/manuales/wordpress/crear/). Si ya tienes, y no te acuerdas de cómo acceder, quizá quieras ver [cómo recuperar tu cuenta de WordPress.org](https://es.wordpress.org/team/handbook/manuales/wordpress/#como-recuperar-tu-cuenta-de-wordpress-org).

## ¿Tienes cuenta de GitHub?

Si tienes cuenta (y ya has accedido), pasa a la siguiente pregunta.

Si no, dale una lectura a [Crear una cuenta en GitHub](https://es.wordpress.org/team/handbook/manuales/github/crear/) y, si quieres, una primera ojeada a [Cómo funciona GitHub](https://es.wordpress.org/team/handbook/manuales/github/comofunciona/) o pregúntale a la persona responsable de la mesa.

## ¿Tienes sincronizada la cuenta de GitHub con WordPress?

Esto es importante para que todo el trabajo que hagas en este repositorio aparezca en [tu perfil de WordPress](https://profiles.wordpress.org/me/).

Si lo tienes, en tu perfil aparecerá tu usuario de GitHub. Si no, puedes leer [Cómo sincronizar tu cuenta de WordPress.org con GitHub](https://es.wordpress.org/team/handbook/manuales/wordpress/sincronizar/).

## Si ya has contestado a todas las preguntas, aquí tienes algunas tareas para hoy…

- [x] #288 
- [x] #289 
- [x] #290

### Tareas de nivel principiante (Prioritarias)

- [x] #235 
- [x] #236

### Tareas de nivel avanzado (Prioritarias)

- [x] #240 
- [x] #241
- [x] #242 

### Tareas Marketing
- [x] #144
- [ ] Crear Issues nuevos para artículos del blog a partir de [esta plantilla](https://github.com/WordPress/spain-handbook/blob/main/.github/ISSUE_TEMPLATE/nuevo-contenido-del-blog.md)

**Comment by moranjosep** [comment]
Jesús, asígname este issue que yo estaré en Torrelodones en la mesa de documentación, creo que Pilar me acompañará en esa mesa también.

Saludos!!

**Comment by estelaris** [comment]
Tareas para la mesa de documentación

1. Revisar la guía de estilo
2. Poner fecha (dia de la semana/hora) para las reuniones semanales de documentación/traducción, similar como lo hacemos en global
3. Planificar, por cuáles artículos comenzamos y crear el proyecto para que todos vayan trabajando en los artículos


@moranjosep estas son las 3 tareas que quisiera llevar a cabo en la mesa de documentación en Torrelodones. Si no te parece, podemos cambiarlas, pero creo que asi es como deberíamos comenzar

**Comment by jesusyesares** [comment]
Gracias @estelaris. Creo que poner día de la semana para poner las reuniones, deberíamos hacerlo más bien en una reunión en remoto, ya que allí no vamos a estar algunos de los que estamos participando ahora mismo. 

Con respecto a planificar los artículos, no sé si estás hablando de los artículos del blog o los del handbook. Si es el handbook, hay una lista de issues plagada de tareas, que está creciendo, a pesar de los pocos que somos.

En principio, hemos estado reuniéndonos unos pocos como proyecto piloto los jueves sobre las 9. No es nada definitivo, y la cosa abrirlo definitivamente a todo el mundo, ya que está planteada la metodología de trabajo, muy centrada en cómo se hace en global, gracias a la ayuda de @javiercasares.

Saludos :)

**Comment by moranjosep** [comment]
Hola @estelaris. Yo no tengo autoridad ni un criterio definido para decidir. Actualmente, ejerzo las funciones de colaborador. Ese rol lo están ejerciendo actualmente @javiercasares y @jesusyesares.

En la WordCamp Zaragoza @AkireOrl presento una propuesta que se preparó para acudir a las WordCamp con un tipo de documentación al estilo de "onboarding" o como incorporarse a la propuesta de documentar, como crear una cuenta de GitHub y como vincularla al perfil de WordPress.

Ese mismo ejercicio lo llevaré preparado para la WordCamp Torrelodones, no obstante, cualquier tema que tú tengas pensado poner en marcha en esa misma WordCamp quedará debidamente documentado y transmitido al resto de los integrantes que no acuden al evento.

A día de hoy existen proyectos marcados como prioritarios. Terminar el manual de GitHub está en cabeza de todos ellos, ya que entendemos que quien no conozca la plataforma será de gran utilidad para comenzar a contribuir en cualquier proyecto.

Un saludo y nos vemos en breve :)

**Comment by estelaris** [comment]
@moranjosep y @jesusyesares 
Mi ponencia en Torre será en cómo contribuir a los equipos de documentación y diseño globales, una vez que esté en línea, espero que la puedan vincular al manual.

Yo solo me refiero al equipo de documentación, el proyecto en que yo estoy involucrada es la traducción de la documentación para usuarios finales (no-desarrolladores) o HelpHub. Yo no me involucro en las decisiones de la comunidad en general pero los apoyo con gusto.

Según veo vamos a tener que definir entre lo que es el trabajo del equipo de documentación y lo que es documentar.  En principio se debe documentar todo lo que sea posible.

Los artículos a los que me refiero son los que estan en https://wordpress.org/documentation/. Nada del handbook o ningun blog. Eventualmente, el equipo de meta pondra las paginas **WW.wordpress.org/documentation/**, (siendo **WW** las letras de cada local y **/documentation/** en el idioma correcto) como parte del rediseno de WordPress.org y los sitios Rosetta. No hay fecha determinada para esto aun.

En cuanto a la reunión que quiero convocar, es una reunión semanal o cada dos semanas con los equipos de documentacion y traduccion para trabajar en la traduccion de lo mencionado arriba. Solo necesito poca gente para decidir, la convocamos y si no funciona para la mayoría, le cambiamos el dia, eso no es problema.

Como dije antes, esto es un proyecto específico y no tiene porque alterar los planes de la comunidad en general.

**Comment by javiercasares** [comment]
Perfecto. Lo que plantea Estela es compatible con lo que se está haciendo. Ahora mismo el foco de documentación es el propio Handbook (sobre todo para aprender) pero el objetivo no es solo contribuir en esto sino también en el resto de documentación global, y, cuando esté, en la parte de localización, que la idea es que la gestione el mismo equipo que el handbook de España.

Por ejemplo, las guías de estilos y demás, podrían estar en este Handbook (a menos que haya algo global con todos los idiomas), pero podemos comenzar desde aquí para preparar todo, y en un futuro escalarlo al lugar definitivo.

Cualquier cosa me decís y vemos dónde colocarlo o preparar tickets y ficheros para facilitar comenzar a redactar (que intuyo que estará en un Google Docs).

**Comment by jesusyesares** [comment]
Por mí, me parece bien hacer una especie de onboarding como el que plantea @estelaris. Si quieres, detállame las tareas para Torrelodones y modificamos el Issue para el contributor.

En cualquier caso, @moranjosep puede estar de apoyo para ayudar a hacer el onboarding en GitHub y ayudar a los asistentes a contribuir.

Lo de establecer unos días, me parece bien. Pero creo que debe quedar abierto a que lo votemos estando los demás implicados, y no solo los asistentes al contributor.

Gracias @estelaris.

**Comment by estelaris** [comment]
Las tareas para Torrelodones son las que plantee arriba para el proyecto de traduccion de la documentacion (HelpHub) solamente. 
Si hay asistentes que necesiten onboarding, les ayudamos y ya.

**Comment by jesusyesares** [comment]
Ok, gracias @estelaris, en cuanto pueda las modifico para que lo tengáis disponible y puedas enseñarlo.
