### ISSUE TITLE
[Documentación] Revisar la guía de estilo

### ISSUE THREAD

**Issue by jesusyesares** [jesusyesares/hb-comunicacion-wordcamp#288]
## Detalles

- Equipo: Documentación
- Descripción breve: Creación del Manual de Estilo en https://github.com/WordPress/spain-handbook/blob/main/manuales/estilos/index.md
- ¿Quieres crear tú el contenido? (Sí o No): 

## Posible ruta del handbook

https://es.wordpress.org/team/handbook/manuales/estilos/

**Comment by estelaris** [comment]
Esta guía de estilo siempre utilizará la guía de estilo del equipo global como base. Utilizar únicamente las secciones que sean pertinentes al idioma español

https://make.wordpress.org/docs/style-guide/

**Comment by estelaris** [comment]
Guia de estilo, borrador: https://docs.google.com/document/d/1QI1SYrmYD0sXke-lM0VDgi4nKljZzYEU5j3R8RdIvKQ/edit?usp=sharing

Dentro del borrador, escoge una sección y pon tu nombre en comentario. Revisaremos en la próxima reunión el viernes 5 de abril, a las 11 a.m. (hora de Espana) en en canal de [Slack Espana](http://wpes.slack.com) #documentacion

**Comment by estelaris** [comment]
Cierro porque ya tenemos otro issue con los avances de la guia de estilo
