### ISSUE TITLE
[Documentación] Poner fecha (día de la semana/hora para las reuniones semanales de documentación/traducción, similar como lo hacemos en global

### ISSUE THREAD

**Issue by jesusyesares** [jesusyesares/hb-comunicacion-wordcamp#289]
## Detalles

- Equipo: Documentación
- Descripción breve: Se hará una propuesta para poner la fecha y hora de las reuniones semanales de documentación.

**Comment by estelaris** [comment]
El equipo decidio continuar con las reuniones semanales los viernes a las 11 hrs. (UTC +1). Las reuniones seran en el Slack de Espana, canal de documentacion.
