### ISSUE TITLE
[Documentación] Planificar por cuáles artículos comenzamos y crear el proyecto para que todos vayan trabajando en los artículos

### ISSUE THREAD

**Issue by jesusyesares** [jesusyesares/hb-comunicacion-wordcamp#290]
## Detalles

- Equipo: Documentación
- Descripción breve: Planificar por cuáles artículos comenzamos y crear el proyecto para que todos vayan trabajando en los artículos

## Tareas

- [ ] #303 
- [ ] #304
- [ ] #305
- [ ] #306
- [ ] #307
- [ ] #308
- [ ] #309
- [ ] #310
- [ ] #311
- [ ] #312

**Comment by estelaris** [comment]
Cierro este issue porque ya tenemos los articulos en issues individuales
