### ISSUE TITLE
[Manual de GitHub] Cómo colaborar en el manual de WordPress España con GitHub

### ISSUE THREAD

**Issue by bertamin** [jesusyesares/hb-comunicacion-wordcamp#338]
## Detalles
Los pasos indicados en el contenido "Cómo colaborar en el manual de WordPress España con GitHub", difieren de lo que aparece publicado en la web de WordPress.
A lo mejor alguno de los contenidos a lo que se hace mención están dentro de otros, pero creo que no esta demás echarlo un vistazo

## Ruta del handbook
[Cómo colaborar en el manual de WordPress España con GitHub](https://github.com/WordPress/spain-handbook/blob/main/manuales/github/index.md#c%C3%B3mo-colaborar-en-el-manual-de-wordpress-espa%C3%B1a-con-github)

## Ruta web WordPress
https://es.wordpress.org/team/handbook/manuales/github/#como-colaborar-en-el-manual-de-wordpress-espana-con-github

Se la asigno a @jesusyesares para que el la pueda asignar a quien corresponda

**Comment by jesusyesares** [comment]
Sí, esos contenidos están ya actualizados en el repositorio y pendientes de publicación. Estoy volviendo a revisarlos para cerrarlo todo.

Gracias @bertamin
