### ISSUE TITLE
[Manual de GitHub] Publicación del Manual de GitHub

### ISSUE THREAD

**Issue by jesusyesares** [jesusyesares/hb-comunicacion-wordcamp#354]
Ruta de publicación: https://es.wordpress.org/team/handbook/manuales/github/

Publicar el manual de GitHub, que se encuentra en la carpeta https://github.com/WordPress/spain-handbook/tree/main/manuales/github

Los archivos o carpetas a publicar en el manual en WordPress son:

- [x] index.md - https://github.com/WordPress/spain-handbook/blob/main/manuales/github/index.md
- [x] crear - https://github.com/WordPress/spain-handbook/blob/main/manuales/github/crear/index.md
- [x] fork - https://github.com/WordPress/spain-handbook/blob/main/manuales/github/fork/index.md
- [x] issues - https://github.com/WordPress/spain-handbook/blob/main/manuales/github/issues/index.md
- [x] fetch - https://github.com/WordPress/spain-handbook/blob/main/manuales/github/fetch/index.md
- [x] rama - https://github.com/WordPress/spain-handbook/blob/main/manuales/github/rama/index.md
- [x] editardocumento - https://github.com/WordPress/spain-handbook/blob/main/manuales/github/editardocumento/index.md
- [x] commit - https://github.com/WordPress/spain-handbook/blob/main/manuales/github/commit/index.md
- [x] pullrequest - https://github.com/WordPress/spain-handbook/blob/main/manuales/github/pullrequest/index.md
- [x] editarimagen - https://github.com/WordPress/spain-handbook/blob/main/manuales/github/editarimagen/index.md
- [x] RETIRAR la página Cómo funciona GitHub

El menú lateral debe quedar de la siguiente manera:

![CleanShot 2024-09-19 at 19 23 53@2x](https://github.com/user-attachments/assets/93dc0c99-403d-4181-b232-c6ab4858c448)

- [x] Crear una cuenta
- [ ] Enlazar tu peril de WordPress (enlazado con https://es.wordpress.org/team/handbook/manuales/wordpress/sincronizar/)
- [x] Crear una copia del repositorio
- [x] Revisar las tareas
- [x] Sincronizar tu copia con el repositorio principal
- [x] Crear una rama en tu copia
- [x] Editar un documento
- [x] Crear  una instantánea de los cambios
- [x] Solicitar revisión de los cambios
- [x] Editar imagen

**Comment by javiercasares** [comment]
El menú del handbook no se puede editar, por lo que los títulos de las páginas coinciden con los del menú y no se pueden añadir enlaces extra.
