### ISSUE TITLE
Man. Git: Crear cuenta .org

### ISSUE THREAD

**Issue by anagavilan** [jesusyesares/hb-comunicacion-wordcamp#39]
Una vez tengamos el manual para entrar a colaborar a la comunidad, donde explicaremos con detalle como hacer la cuenta en .org.
Modificar el manual de Github en el apartado 2 "Enlazar perfiles WordPress y Github"  y agregar una frase tipo: si aún no tienes cuenta en .org sigue las siguientes instrucciones, con enlace a ese apartado.

**Comment by javiercasares** [comment]
En #51 hay una pequeña explicación de ello (para el Contributor Day).

**Comment by javiercasares** [comment]
Se hace en el ticket #123
