### ISSUE TITLE
Aviso de estado provisional del documento

### ISSUE THREAD

**Issue by AlexMusetti** [jesusyesares/hb-comunicacion-wordcamp#46]
Aviso documento **en elaboración**

Este documento está en proceso de elaboración. Ten en cuenta que es probable que encuentres incorrecciones y/o información errónea u obsoleta puesto que es un borrador. 
Te avisaremos cuando esté listo.
Si tienes alguna sugerencia o aportación, te agradeceremos que nos lo hagas saber contactando con el responsable de este proyecto (Nombre del responsable) a través del canal de WP-Marketing en Slack.
Gracias (por respetar el trabajo de este equipo y) por interesarte en el proyecto.

Aviso documento **en revisión**

Este documento está en proceso de revisión. Si encuentras alguna errata o incorrección, te agradeceremos que nos lo hagas saber contactando con el responsable de este proyecto (Nombre del responsable) a través del canal de WP-Marketing en Slack.
Gracias por interesarte en el proyecto.

**Comment by jesusyesares** [comment]
Lo veo correcto, en el primer texto, quizá en el agradecimiento quitaría lo que está en el paréntesis y agradecería solamente el interés en el proyecto.

Por lo demás, creo que es lo que buscábamos.

**Comment by bertamin** [comment]
De acuerdo, con ambos textos. 

Si acaso lo que dice Jesús de quitar lo del parentesis pero por lo demás OK.

**Comment by AlexMusetti** [comment]
Pues eliminamos el paréntesis (que además suena un poco pasivo agresivo ja ja).
Jesús, copias el texto de la issue cuando lo vayas a necesitar o prefieres que lo edite en algún otro sitio?

**Comment by jesusyesares** [comment]
Genial, ya lo he añadido al documento.
